name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60341eafe0192f3523be280be5a91ee4a67a35c85da496d3ef25b201515d0111"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
