name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c7b445a5ca2bfab0bfdfdcaba62d1a4365c74c9a6c52e658f1debfb98bf4045"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
