name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0117ba48b2bb46d81ec6ac10895cef28195b86d89989a1d6de8e370e0930aca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
