name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4be45a50c6f511d66a20a84aafc6675c7f42f488f3f4dd1c76035bbada13d357"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
