name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b8260c57388ea77ef6ddd71c00e69d01b6da0fcc642c0e3733b7644c417dbb2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
