name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ba010c9c75c4ff6d7e08d401181d5344278e62ed3af1f48898442b11d6bd834"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
