name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd42660174542e9ac1d9b87988788d136e1f5e3d2ffce4d6735fa94ede710092"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
