name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a3f22c9b0730e80825789e9426fd5f144bce428f4c4a24e5c9ab564254bb8dc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
