name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afc78f93b1e5b9309a447e3e21cc5586d6528a8ffa7059bd460e5c434dc33df7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
