name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52cd5305d8bf0b0efdc39db6792eda45317b744e3789a92d01bfc5a0a92b1805"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
