name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4da687c31defc207b8e9af6fa3733916f95063985661597c59b64c0115f5d886"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
