name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d20005055287590e0bedd80eb55d10295a774e8e28d4bd9af66e7845d582c1b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
