name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fe957a313e0da7c31f6627b85d152ca70e1bb00de62039759aa8886914a3caf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
