name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0b3c77a1f493a699ec6de164f9bff86024e461574608832d8c25090f59171d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
