name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f5e2494683b164188b7099979d50e7a21beab15ded3a8d344e37e57ce03e572"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
