name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d49ddc469a19e9f36a557d7383ead70174d47dacc12233726c94d591807889e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
