name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed98f6add627df63dce564c8b53bcd7230876ca8d871fec2ac86ebbca9d4bf28"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
