name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9cac75ed37f60a1eaeb01a6fb208d3befdd244e87fb46fb168c3f61b8130caa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
