name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0e719c08a02e645679b47c918c490a56335e1bebc98224781a0fdfde9901f8f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
