name = "FuzzCraft 3"
author = "FuzzyMelon94"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5d9603c3e130345e7a55b2b929c3a0cab4651f8d3eca00dbc347be424993cd6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "./config/paxi/datapacks"
